<a href="https://colab.research.google.com/github/Rathorerishabh/PRODIGY_DS_01/blob/main/FOODCLASSIFICATIONANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FOOD CLASSIFICATION USING ARTIFICIAL NEURAL NETWORK IN DEEP LEARNING


In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [25]:
!pip install scikeras

In [3]:
df=pd.read_csv("food classification.csv")

In [4]:
df

Unnamed: 0  Calories  Total Fat  Saturated Fat  Monounsaturated Fat  \
0               0     149.0          0            0.0                  0.0   
1               1     123.0          0            0.0                  0.0   
2               2     150.0          0            0.0                  0.0   
3               3     110.0          0            0.0                  0.0   
4               4     143.0          0            0.0                  0.0   
...           ...       ...        ...            ...                  ...   
13255       13255     140.0          5            1.0                  0.0   
13256       13256     130.0          4            0.5                  0.0   
13257       13257     140.0          3            0.0                  0.0   
13258       13258     140.0          3            0.5                  0.0   
13259       13259     120.0          4            0.5                  0.0   

       Polyunsaturated Fat  Trans Fat  Cholesterol  Sodium  \
0                      0.0        0.0            0     9.0   
1                      0.0        0.0            0     5.0   
2                      0.0        0.0            0     4.0   
3                      0.0        0.0            0     6.0   
4                      0.0        0.0            0     7.0   
...                    ...        ...          ...     ...   
13255                  0.0        0.0            0    60.0   
13256                  0.0        0.0            0    50.0   
13257                  0.0        0.0            0   130.0   
13258                  0.0        0.0            0    55.0   
13259                  0.0        0.0            0    55.0   

       Total Carbohydrate  Dietary Fiber  Sugars  Sugar Alcohol  Protein  \
0                     9.8            0.0     0.0              0      1.3   
1                     6.6            0.0     0.0              0      0.8   
2                    11.4            0.0     0.0              0      1.3   
3                     7.0            0.0     0.0              0      0.8   
4                    13.1            0.0     0.0              0      1.0   
...                   ...            ...     ...            ...      ...   
13255                23.0            2.0    13.0              0      2.0   
13256                23.0            1.0    14.0              0      2.0   
13257                26.0            2.0    15.0              0      1.0   
13258                27.0            2.0    17.0              0      1.0   
13259                23.0            2.0    13.0              0      2.0   

       Vitamin A  Vitamin C  Calcium  Iron            class  
0              0          0        0     0  'In Moderation'  
1              0          0        0     0  'In Moderation'  
2              0          0        0     0  'In Moderation'  
3              0          0        0     0  'In Moderation'  
4              0          0        0     0  'In Moderation'  
...          ...        ...      ...   ...              ...  
13255          0          0        0     4  'In Moderation'  
13256          0          0        0     4  'In Moderation'  
13257          0          0        0     2  'In Moderation'  
13258          0          0        0     2  'In Moderation'  
13259          0          0        0     4  'In Moderation'  

[13260 rows x 19 columns]

In [7]:
df=df.drop("Unnamed: 0",axis=1,inplace=True)


KeyError: "['Unnamed: 0'] not found in axis"

In [8]:
df

Calories  Total Fat  Saturated Fat  Monounsaturated Fat  \
0         149.0          0            0.0                  0.0   
1         123.0          0            0.0                  0.0   
2         150.0          0            0.0                  0.0   
3         110.0          0            0.0                  0.0   
4         143.0          0            0.0                  0.0   
...         ...        ...            ...                  ...   
13255     140.0          5            1.0                  0.0   
13256     130.0          4            0.5                  0.0   
13257     140.0          3            0.0                  0.0   
13258     140.0          3            0.5                  0.0   
13259     120.0          4            0.5                  0.0   

       Polyunsaturated Fat  Trans Fat  Cholesterol  Sodium  \
0                      0.0        0.0            0     9.0   
1                      0.0        0.0            0     5.0   
2                      0.0        0.0            0     4.0   
3                      0.0        0.0            0     6.0   
4                      0.0        0.0            0     7.0   
...                    ...        ...          ...     ...   
13255                  0.0        0.0            0    60.0   
13256                  0.0        0.0            0    50.0   
13257                  0.0        0.0            0   130.0   
13258                  0.0        0.0            0    55.0   
13259                  0.0        0.0            0    55.0   

       Total Carbohydrate  Dietary Fiber  Sugars  Sugar Alcohol  Protein  \
0                     9.8            0.0     0.0              0      1.3   
1                     6.6            0.0     0.0              0      0.8   
2                    11.4            0.0     0.0              0      1.3   
3                     7.0            0.0     0.0              0      0.8   
4                    13.1            0.0     0.0              0      1.0   
...                   ...            ...     ...            ...      ...   
13255                23.0            2.0    13.0              0      2.0   
13256                23.0            1.0    14.0              0      2.0   
13257                26.0            2.0    15.0              0      1.0   
13258                27.0            2.0    17.0              0      1.0   
13259                23.0            2.0    13.0              0      2.0   

       Vitamin A  Vitamin C  Calcium  Iron            class  
0              0          0        0     0  'In Moderation'  
1              0          0        0     0  'In Moderation'  
2              0          0        0     0  'In Moderation'  
3              0          0        0     0  'In Moderation'  
4              0          0        0     0  'In Moderation'  
...          ...        ...      ...   ...              ...  
13255          0          0        0     4  'In Moderation'  
13256          0          0        0     4  'In Moderation'  
13257          0          0        0     2  'In Moderation'  
13258          0          0        0     2  'In Moderation'  
13259          0          0        0     4  'In Moderation'  

[13260 rows x 18 columns]

In [10]:
x=df.drop("class",axis=1)
y=df["class"]

In [15]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y1=lb.fit_transform(y)
y=pd.get_dummies(y).values

In [16]:
y1

array([0, 0, 0, ..., 0, 0, 0])

In [19]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=uint8)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=46)

In [22]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [27]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from scikeras.wrappers import KerasClassifier,KerasRegressor

In [91]:
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units= 30,kernel_initializer='glorot_uniform',activation='ReLU',input_dim = 17))


# Adding the second hidden layer
classifier.add(Dense(units = 13,kernel_initializer='glorot_uniform',activation='ReLU'))
classifier.add(Dense(units = 14,kernel_initializer='glorot_uniform',activation='ReLU'))


# Adding the output layer
classifier.add(Dense(units = 10,kernel_initializer='glorot_uniform',activation='ReLU'))



# Adding the output layer
classifier.add(Dense(units= 3, activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'Adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
model_history=classifier.fit(x_train, y_train,validation_split=0.33, batch_size = 10, epochs = 100)

Epoch 1/100
622/622 [==============================] - 3s 3ms/step - loss: 0.6078 - accuracy: 0.7345 - val_loss: 0.4746 - val_accuracy: 0.7918
Epoch 2/100
622/622 [==============================] - 2s 3ms/step - loss: 0.4229 - accuracy: 0.8170 - val_loss: 0.3906 - val_accuracy: 0.8345
Epoch 3/100
622/622 [==============================] - 2s 3ms/step - loss: 0.3839 - accuracy: 0.8324 - val_loss: 0.3647 - val_accuracy: 0.8456
Epoch 4/100
622/622 [==============================] - 2s 3ms/step - loss: 0.3594 - accuracy: 0.8456 - val_loss: 0.3693 - val_accuracy: 0.8473
Epoch 5/100
622/622 [==============================] - 2s 4ms/step - loss: 0.3486 - accuracy: 0.8508 - val_loss: 0.3440 - val_accuracy: 0.8590
Epoch 6/100
622/622 [==============================] - 2s 3ms/step - loss: 0.3321 - accuracy: 0.8586 - val_loss: 0.3563 - val_accuracy: 0.8453
Epoch 7/100
622/622 [==============================] - 2s 3ms/step - loss: 0.3233 - accuracy: 0.8638 - val_loss: 0.3481 - val_accuracy: 0.8541

In [92]:
y_pred=classifier.predict(x_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)
y_pred_class

125/125 [==============================] - 0s 1ms/step


array([1, 1, 0, ..., 1, 2, 0])

In [93]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.90      0.89      0.90      2001
           1       0.88      0.92      0.90      1702
           2       0.94      0.80      0.86       275

    accuracy                           0.89      3978
   macro avg       0.91      0.87      0.89      3978
weighted avg       0.90      0.89      0.89      3978

[[1780  207   14]
 [ 141 1560    1]
 [  51    4  220]]


(17,)

In [94]:
def create_model(neurons=30):
  model =Sequential()
  model.add(Dense(units=neurons,activation='relu',input_dim = 17))
  model.add(Dense(units = 13,activation='relu'))
  model.add(Dense(units = 14,activation='relu'))
  model.add(Dense(units = 10,activation='relu'))
  model.add(Dense(units = 3,activation='Softmax'))
  model.compile(optimizer = 'Adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
  return model

In [95]:
base_model=KerasClassifier(build_fn=create_model,verbose=0,batch_size=10,epochs=100,neurons=30)
base_model.fit(x_train,y_train,epochs=100)

/usr/local/lib/python3.10/dist-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)


KerasClassifier(
	model=None
	build_fn=<function create_model at 0x7ae7551b6830>
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=10
	validation_batch_size=None
	verbose=0
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=100
	neurons=30
	class_weight=None
)

In [96]:
best_score=base_model.score(x_test,y_test)
best_score

0.9092508798391151

In [97]:
y_pred = base_model.predict(x_test)

# Ensure y_pred is in the correct format for classification_report
y_pred1 = np.argmax(y_pred, axis=1)  # Convert one-hot encoded predictions to class labels

# Get the classification report


In [98]:
print(classification_report(y_test_class,y_pred1))
print(confusion_matrix(y_test_class,y_pred1))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91      2001
           1       0.90      0.92      0.91      1702
           2       0.87      0.91      0.89       275

    accuracy                           0.91      3978
   macro avg       0.90      0.91      0.90      3978
weighted avg       0.91      0.91      0.91      3978

[[1799  165   37]
 [ 134 1567    1]
 [  22    2  251]]


Hyperparameter Tuning using RandomizedSearchCV FOR ANN


In [78]:
from sklearn.model_selection import RandomizedSearchCV

In [79]:
batch_size=[10,20,30,40,60,80,100]
epochs=[1,3,10,20,50,100,150]
neurons =[1,10,20,30,40]
params=dict(batch_size=batch_size,epochs=epochs,neurons=neurons)
params

{'batch_size': [10, 20, 30, 40, 60, 80, 100],
 'epochs': [1, 3, 10, 20, 50, 100, 150],
 'neurons': [1, 10, 20, 30, 40]}

In [86]:
search=RandomizedSearchCV(estimator=base_model,param_distributions=params,cv=3)


In [87]:
search_result=search.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/usr/local/lib/python3.10/dist-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/usr/local/lib/python3.10/dist-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/usr/local/lib/python3.10/dist-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
/usr/local/lib/python3.10/dist-packages/scikeras

In [88]:
search_result

RandomizedSearchCV(cv=3,
                   estimator=KerasClassifier(batch_size=20, build_fn=<function create_model at 0x7ae76e4e8af0>, epochs=100, neurons=10, verbose=0),
                   param_distributions={'batch_size': [10, 20, 30, 40, 60, 80,
                                                       100],
                                        'epochs': [1, 3, 10, 20, 50, 100, 150],
                                        'neurons': [1, 10, 20, 30, 40]})

In [90]:
best_params = search_result.best_params_
best_params

{'neurons': 30, 'epochs': 100, 'batch_size': 10}